Repository pinluis/AirlineDelay, pull requests merged in 2023-05, with the labels that each got.

#7 Initialization of app
  app/app.py
  app/frontend/index.html
  app/frontend/result.html
  requirements.txt
Labels: enhancement

#9 Finalization App
  README.md
  app/app.py
  app/frontend/index.html
  app/predict.py
  app/static/images/loading.gif
  data/airlines_delay_cleaned_unique_airline.csv
  data/airlines_delay_cleaned_unique_airport.csv
  src/2-TrainingLogisticRegression.ipynb
  src/CleanedUniqueData.ipynb
Labels: documentation, enhancement

#8 enhanced eda, analysis and data cleansing
  .vscode/settings.json
  requirements.txt
  src/1-AirlineDelay.ipynb
  src/AirlineDelay slides.html
  src/AirlineDelay slides_files/240_F_511442590_iFJ5ppFxiWdb2sWx0Yd3SX9RynRHMfRk.jpg
  src/AirlineDelay slides_files/MathJax.js.Download
  src/AirlineDelay slides_files/jquery.min.js.Download
  src/AirlineDelay slides_files/notes.js.Download
  src/AirlineDelay slides_files/require.min.js.Download
  src/AirlineDelay slides_files/reveal.css
  src/AirlineDelay slides_files/reveal.js.Download
  src/AirlineDelay slides_files/simple.css
Labels: documentation, enhancement

#10 Bugfix
  app/frontend/index.html
Labels: bug

#14 Slides and cleanup
  README.md
  Slides/1-AirlineDelay.slides.html
  Slides/2-TrainingLogisticRegression slides_files/MathJax.js.Download
  Slides/2-TrainingLogisticRegression slides_files/jquery.min.js.Download
  Slides/2-TrainingLogisticRegression slides_files/require.min.js.Download
  Slides/2-TrainingLogisticRegression slides_files/reveal.css
  Slides/2-TrainingLogisticRegression slides_files/reveal.js.Download
  Slides/2-TrainingLogisticRegression slides_files/simple.css
  Slides/2-TrainingLogisticRegression.slides.html
  Slides/3-TrainingRandomForrest.slides.html
  Slides/4-ModelComparison.slides.html
  Slides/AirlineDelay slides_files/240_F_511442590_iFJ5ppFxiWdb2sWx0Yd3SX9RynRHMfRk.jpg
  Slides/AirlineDelay slides_files/MathJax.js.Download
  Slides/AirlineDelay slides_files/jquery.min.js.Download
  Slides/AirlineDelay slides_files/notes.js.Download
  Slides/AirlineDelay slides_files/require.min.js.Download
  Slides/AirlineDelay slides_files/reveal.css
  Slides/AirlineDelay slides_files/reveal.js.Download
  Slides/AirlineDelay slides_files/simple.css
  src/2-TrainingLogisticRegression.ipynb
  src/3-TrainingRandomForrest.ipynb
  src/4-ModelComparison.ipynb
Labels: documentation, enhancement
